<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>HireLens.Bff</RootNamespace>
    <AssemblyName>HireLens.Bff</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="HireLens.Unit.Tests" />
  </ItemGroup>
</Project>
