---
applications:
  - name: hirelens-api
    memory: 1G
    instances: 1
    timeout: 180
    docker:
      image: ghcr.io/OWNER/hirelens-api:latest
    routes:
      - route: hirelens-api.cfapps.eu20-002.hana.ondemand.com
    services:
      - hana_dev
      - hirelens-xsuaa
      - hirelens-objectstore
      - hirelens-auditlog
    env:
      ASPNETCORE_ENVIRONMENT: Production
      PUBLIC_HOST: hirelens-web.cfapps.eu20-002.hana.ondemand.com

  - name: hirelens-worker
    memory: 1G
    instances: 1
    timeout: 180
    no-route: true
    docker:
      image: ghcr.io/OWNER/hirelens-worker:latest
    services:
      - hana_dev
      - hirelens-xsuaa
      - hirelens-objectstore
      - hirelens-auditlog
    env:
      ASPNETCORE_ENVIRONMENT: Production

  - name: hirelens-web
    memory: 1G
    instances: 1
    timeout: 180
    lifecycle: docker
    docker:
      image: ghcr.io/OWNER/hirelens-web:latest
    routes:
      - route: hirelens-web.cfapps.eu20-002.hana.ondemand.com
      - route: dev-2z4ga5d8-hirelens-web.cfapps.eu20-002.hana.ondemand.com
    services:
      - hirelens-xsuaa
    env:
      ASPNETCORE_ENVIRONMENT: Production
      PUBLIC_HOST: hirelens-web.cfapps.eu20-002.hana.ondemand.com
      API_URL: https://hirelens-api.cfapps.eu20-002.hana.ondemand.com
